development:
  adapter: postgresql
  encoding: unicode
  database: gemini_development
  pool: 5
  username: postgres
  password: marc

test:
  adapter: postgresql
  encoding: unicode
  database: gemini_test
  pool: 5
  username: postgres
  password: marc
