require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InterestedUsersController do

  # This should return the minimal set of attributes required to create a valid
  # InterestedUser. As you add validations to InterestedUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InterestedUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all interested_users as @interested_users" do
      interested_user = InterestedUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:interested_users).should eq([interested_user])
    end
  end

  describe "GET show" do
    it "assigns the requested interested_user as @interested_user" do
      interested_user = InterestedUser.create! valid_attributes
      get :show, {:id => interested_user.to_param}, valid_session
      assigns(:interested_user).should eq(interested_user)
    end
  end

  describe "GET new" do
    it "assigns a new interested_user as @interested_user" do
      get :new, {}, valid_session
      assigns(:interested_user).should be_a_new(InterestedUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested interested_user as @interested_user" do
      interested_user = InterestedUser.create! valid_attributes
      get :edit, {:id => interested_user.to_param}, valid_session
      assigns(:interested_user).should eq(interested_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InterestedUser" do
        expect {
          post :create, {:interested_user => valid_attributes}, valid_session
        }.to change(InterestedUser, :count).by(1)
      end

      it "assigns a newly created interested_user as @interested_user" do
        post :create, {:interested_user => valid_attributes}, valid_session
        assigns(:interested_user).should be_a(InterestedUser)
        assigns(:interested_user).should be_persisted
      end

      it "redirects to the created interested_user" do
        post :create, {:interested_user => valid_attributes}, valid_session
        response.should redirect_to(InterestedUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interested_user as @interested_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterestedUser.any_instance.stub(:save).and_return(false)
        post :create, {:interested_user => {}}, valid_session
        assigns(:interested_user).should be_a_new(InterestedUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterestedUser.any_instance.stub(:save).and_return(false)
        post :create, {:interested_user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interested_user" do
        interested_user = InterestedUser.create! valid_attributes
        # Assuming there are no other interested_users in the database, this
        # specifies that the InterestedUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InterestedUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => interested_user.to_param, :interested_user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested interested_user as @interested_user" do
        interested_user = InterestedUser.create! valid_attributes
        put :update, {:id => interested_user.to_param, :interested_user => valid_attributes}, valid_session
        assigns(:interested_user).should eq(interested_user)
      end

      it "redirects to the interested_user" do
        interested_user = InterestedUser.create! valid_attributes
        put :update, {:id => interested_user.to_param, :interested_user => valid_attributes}, valid_session
        response.should redirect_to(interested_user)
      end
    end

    describe "with invalid params" do
      it "assigns the interested_user as @interested_user" do
        interested_user = InterestedUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterestedUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => interested_user.to_param, :interested_user => {}}, valid_session
        assigns(:interested_user).should eq(interested_user)
      end

      it "re-renders the 'edit' template" do
        interested_user = InterestedUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterestedUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => interested_user.to_param, :interested_user => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interested_user" do
      interested_user = InterestedUser.create! valid_attributes
      expect {
        delete :destroy, {:id => interested_user.to_param}, valid_session
      }.to change(InterestedUser, :count).by(-1)
    end

    it "redirects to the interested_users list" do
      interested_user = InterestedUser.create! valid_attributes
      delete :destroy, {:id => interested_user.to_param}, valid_session
      response.should redirect_to(interested_users_url)
    end
  end

end
